apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  # A TLS-t majd az ingress-nginx terminálja, az Argo CD mögötte HTTP-n áll.
  # Enélkül végtelen átirányítási hurokba futsz az Ingress mögött.
  server.insecure: "true"
