apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: minishop-kristof
spec:
  encryptedData:
    SHOP_API_KEY: AgBaCHfzf0zHUIwHubV1hvMwFyumoa+SyBj6J1FryhDuO8SmKgsIZR59g0F1q0U4xJTaMaF2CEn0pvIpNmhBZDYkdy4zpfG4ltGuiZtRta7ucUZ4E/3KvI5wSgrv+PF8oCnkJtVJ4GDrEg6WX7y9nW30jjYVuGivNtJvdd5pcqoGzoPuURXhAHzy4NBfYh5AnWqUZRUVaB1Xo9bsoUWgqtRJf5/ydlq37/66b6MRoakb/BpLiSfLsBQwvIVBmZZcKgoYjqqqjN0xFsBW0u6EyDwAf3wf5SorsZzkppBszdSIOYlnc1pBZI8D0GjubIAeVoxd8srMmeS8Qt0LbVI+2w8/QlC3bbU5Dre37rGW8CeiEyGLdjvo5T1g31V7cUSdIyLglUUUT8mIjRkym/W/HEj0+5A/Tni0+38WMcX7NgZwIH0t7CokZHkEfVnF3V+h0eEGrcaP+9Q/OyB3JIWtTtLe5DHHOhrP73CghqBUfhIQFnBFdBVa7R7Ldy44NB4XhmFrJVD5Dd1WKpj1Wj4QN9iorBbc6SZp6TEO8dLsrDCLj/NpoPECxqdMqtc97ltntXfgkCfFkaVYOHouF65zaPhqK49PAkA/WBlvvwysA6cdYaD08UYrag8tXg/gfgSqxEiZNO/i48cHwtcFcjqIgCT64VsLjXsfUMWBJDsewPVewoQUDrh0MHQDGr2gvk4EQz4M3QI8TTVIquOrnC/wDD8JI5K7QMRcFA==
  template:
    metadata:
      name: app-secret
      namespace: minishop-kristof
