apiVersion: apps/v1
kind: Deployment
metadata:
  name: minishop-kristof-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minishop-kristof-redis
  template:
    metadata:
      labels:
        app: minishop-kristof-redis
    spec:
      containers:
        - name: podinfo
          image: redis:7.4-alpine
          ports:
            - name: http
              containerPort: 9898
          envFrom:
            - configMapRef:
                name: minishop-kristof-config # a nevét a kustomize írja át – lásd lentebb
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 15
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              memory: 128Mi