apiVersion: apps/v1
kind: Deployment
metadata:
  name: minishop-kristof-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minishop-kristof-web
  template:
    metadata:
      labels:
        app: minishop-kristof-web
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.7.1
          ports:
            - name: http
              containerPort: 9898
          envFrom:
            - configMapRef:
                name: minishop-kristof-config # a nevét a kustomize írja át – lásd lentebb
            - secretRef:
                name: minishop-kristof-secret
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 15
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              memory: 128Mi