apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minishop-kristof

resources:
  - deployment-web.yaml
  - service-web.yaml
  - deployment-redis.yaml
  - service-redis.yaml
  
configMapGenerator:
  - name: minishop-kristof-config
    literals:
      - PODINFO_UI_COLOR=#34577c
      - PODINFO_UI_MESSAGE=Elso verzio - GitOps labor
      - CACHE_URL=minishop-kristof-redis
