apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minishop-kristof

resources:
  - deployment-web.yaml
  - service-web.yaml
  - deployment-redis.yaml
  - service-redis.yaml
  - ingress.yaml
  - app-secret.yaml
  - service-monitor.yaml
  - grafana-dashboard.yaml
  
configMapGenerator:
  - name: minishop-kristof-config
    literals:
      - PODINFO_UI_COLOR=#00FFDF
      - PODINFO_UI_MESSAGE=Kristof Labor
      - CACHE_URL=minishop-kristof-redis
