apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  namespace: minishop-kristof
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: minishop-kristof-web

  namespaceSelector:
    matchNames:
      - minishop-kristof

  endpoints:
    - port: http
      path: /metrics
      interval: 15s