apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: sealed-secrets
    targetRevision: 2.19.1        # ellenőrizd a legfrissebbet
    helm:
      valuesObject:
        fullnameOverride: sealed-secrets-controller
        # a kubeseal CLI alapból a 'sealed-secrets-controller' nevet keresi,
        # ezért nevezzük így el, hogy ne kelljen külön flag
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true